packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: ^3.25.49
  '@tanstack/react-query': ^5.80.7
  '@trpc/client': ^11.4.0
  '@trpc/tanstack-react-query': ^11.4.0
  '@trpc/server': ^11.4.0
catalogs:
  react19:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.1
    '@types/react-dom': ^18.3.1
ignoredBuiltDependencies:
  - react-native-nitro-modules
onlyBuiltDependencies:
  - esbuild
